<?php
declare(strict_types=1);

class MyModuleTestModuleFrontController extends ModuleFrontController
{
    public function initContent()
    {
        parent::initContent();
        $this->context->smarty->assign([
            'data' => "salut pandore"
        ]);
        $this->setTemplate('module:mymodule/views/templates/front/test.tpl');
    }

    public function postProcess()
    {
        //postProcess executed before initContent
        if(Tools::isSubmit('form')) {
            return Tools::redirect("URL");
        }
        parent::postProcess(); // TODO: Change the autogenerated stub
    }
}